# Generated by Django 3.2.7 on 2021-11-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='film',
        ),
        migrations.AddField(
            model_name='comment',
            name='films',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='serials.product'),
            preserve_default=False,
        ),
    ]
