# Generated by Django 3.2.7 on 2021-11-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
        ('comments', '0002_auto_20211117_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='serials.product'),
        ),
    ]
