# Generated by Django 3.2.7 on 2021-11-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
